#!/bin/bash
jq -r '. as $p | "\($p.name) is of type \($p.types[0].type.name|ascii_upcase), weighs \($p.weight/10)kg, and is \($p.height/10)m tall."' data.json | sed 's/\([0-9][0-9]*\.[0-9]\)0*/\1/g' | awk '{print}'
