#!/bin/bash
jq -r '. as $p | [$p.name, $p.types[0].type.name, ($p.weight/10), ($p.height/10)] | @tsv' data.json | awk -F'\t' '{printf "%s is of type %s, weighs %skg, and is %sm tall.\n", $1, toupper(substr($2,1,1)) substr($2,2), $3, $4}' | sed 's/\.0kg/kg/g; s/\.0m/m/g'
